Vagrant.configure("2") do |config|
  config.vm.box = "ambalabanov/rhel"
  config.vm.box_version = "2.0.0"
  config.vm.provider "parallels" do |prl|
    prl.name = "Red Hat Enterprise Linux 8.5"
    prl.linked_clone = false
    prl.customize ["set", :id, "--distribution", "rhel"]
  end
end
